import Link from "next/link";
import { ArrowLeft, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";

export const dynamic = "force-static";

export const metadata = {
  title: "Terms of Service | AGENTIA",
  description: "Terms of Service governing your use of AGENTIA AI platform and services."
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-[#080B10] text-slate-100 font-sans antialiased selection:bg-cyan-500/20 selection:text-cyan-200">
      <header className="border-b border-[#3A4658]/40 bg-[#0F141C]/80 backdrop-blur-md sticky top-0 z-50">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
          <Link href="/" className="flex items-center gap-2 text-sm font-semibold text-slate-300 hover:text-white transition-colors">
            <ArrowLeft className="h-4 w-4" />
            Back to AGENTIA
          </Link>
          <div className="flex items-center gap-2 font-black tracking-tight text-white">
            <FileText className="h-5 w-5 text-cyan-400" />
            AGENTIA Terms of Service
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-12">
        <div className="rounded-2xl border border-[#3A4658]/50 bg-[#151B24] p-8 shadow-2xl md:p-12 space-y-8">
          <div>
            <span className="rounded-full bg-cyan-500/10 px-3 py-1 text-xs font-semibold text-cyan-400 border border-cyan-500/20">
              Effective Date: July 31, 2026
            </span>
            <h1 className="mt-4 text-3xl font-black text-white md:text-4xl tracking-tight">Terms of Service</h1>
            <p className="mt-3 text-slate-300 text-base leading-relaxed">
              Welcome to AGENTIA (&quot;Platform&quot;), operated at <strong className="text-white">https://www.agentia-ai.cloud</strong>. 
              By accessing or using AGENTIA, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not access or use our services.
            </p>
          </div>

          <hr className="border-[#3A4658]/40" />

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-white">1. Acceptance of Terms</h2>
            <p className="text-slate-300 text-sm leading-relaxed">
              By creating an account, connecting via Google OAuth, or using our AI agent workspace, you confirm that you are at least 18 years old or possess legal parental consent, and possess the authority to agree to these Terms.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-white">2. Description of Services & Daily Credits</h2>
            <p className="text-slate-300 text-sm leading-relaxed">
              AGENTIA provides an AI-powered agent orchestration platform that assists users with general chat, code generation, mathematical analysis, document processing, and vision tasks.
            </p>
            <ul className="list-disc pl-5 space-y-2 text-sm text-slate-300">
              <li>Each user account is allocated daily request credits reset every 24 hours.</li>
              <li>Requests consume credits according to task complexity (e.g. normal chat: 1 credit, coding: 2 credits, vision: 5 credits).</li>
              <li>Rate limits and anti-abuse mechanisms apply to ensure service availability for all users.</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-white">3. Acceptable Use Policy</h2>
            <p className="text-slate-300 text-sm leading-relaxed">
              You agree not to misuse AGENTIA or assist others in doing so. Prohibited activities include:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-sm text-slate-300">
              <li>Generating harmful, illegal, defamatory, or malicious content.</li>
              <li>Attempting to reverse-engineer, exploit, or bypass rate limits or authentication security controls.</li>
              <li>Automated scraping or abusive API spamming without prior written consent.</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-white">4. Intellectual Property & AI Output</h2>
            <p className="text-slate-300 text-sm leading-relaxed">
              You retain ownership of the prompts and document inputs you provide. Output generated by AGENTIA models is made available for your personal or commercial use in accordance with applicable laws.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-white">5. Disclaimer of Warranties & Limitation of Liability</h2>
            <p className="text-slate-300 text-sm leading-relaxed">
              AGENTIA is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis. While we strive for maximum precision and uptime, AI models may occasionally produce incorrect or incomplete information. AGENTIA shall not be held liable for decisions made based on automated AI outputs.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-white">6. Modifications & Contact</h2>
            <p className="text-slate-300 text-sm leading-relaxed">
              We reserve the right to modify these Terms at any time. Continued use of the platform constitutes acceptance of updated terms. For inquiries, contact:
            </p>
            <div className="rounded-xl border border-[#3A4658]/50 bg-[#0F141C] p-4 text-sm text-slate-300">
              <p><strong className="text-white">AGENTIA Legal & Operations</strong></p>
              <p>Email: Zyad.2524033@stemelsadat.moe.edu.eg</p>
              <p>Website: https://www.agentia-ai.cloud</p>
            </div>
          </section>

          <div className="pt-4 flex justify-between items-center border-t border-[#3A4658]/40">
            <Link href="/privacy" className="text-sm font-semibold text-cyan-400 hover:text-cyan-300 transition-colors">
              &larr; Read Privacy Policy
            </Link>
            <Link href="/dashboard">
              <Button variant="secondary" size="sm">Go to Dashboard</Button>
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
